using Google.GenAI;
using Google.GenAI.Types;

namespace Api.Services;

public interface IAdviceService
{
    Task<string> GenerateAdviceAsync(string doctorQuery, string cohortSummary);
}

public class AdviceService : IAdviceService
{
    private readonly Client _client;
    private readonly string _model;
    private readonly ILogger<AdviceService> _logger;

    public AdviceService(
        IConfiguration config,
        ILogger<AdviceService> logger)
    {
        var geminiSection = config.GetSection("Gemini");
        var apiKey = geminiSection["ApiKey"];
        
        // If API key is in config, use it; otherwise SDK picks up GEMINI_API_KEY env var
        _client = !string.IsNullOrEmpty(apiKey) 
            ? new Client(apiKey: apiKey) 
            : new Client();
        
        _model = geminiSection["Model"] ?? "gemini-2.5-flash";
        _logger = logger;
    }

    public async Task<string> GenerateAdviceAsync(string doctorQuery, string cohortSummary)
    {
        // Build prompt
        var prompt = $@"
You are a clinical decision support assistant.

Doctor question:
{doctorQuery}

Cohort summary from MIMIC-III:
{cohortSummary}

Tasks:
1. Briefly summarize the cohort evidence in 2–3 bullet points.
2. Suggest up to 3 likely differential diagnoses (with ICD-9 codes if obvious).
3. Suggest up to 5 useful lab tests or imaging studies.
4. Suggest up to 5 commonly used medications or interventions from the cohort
   that might be considered (doses NOT required).
5. Add a final reminder: this is not a substitute for clinical judgment.";

        try
        {
            var response = await _client.Models.GenerateContentAsync(
                model: _model,
                contents: prompt
            );

            if (response.Candidates == null || response.Candidates.Count == 0)
                return "No advice generated by LLM.";

            var text = response.Candidates[0].Content.Parts[0].Text;
            return text ?? "No advice generated by LLM.";
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error calling Gemini advice API.");
            return "Error generating AI advice. Please try again later.";
        }
    }
}
